[package]
name = "zed-dl"
version = "0.1.0"
edition = "2021"

[dependencies]
octocrab = "0.39.0"
reqwest = "0.12.7"
tokio = { version = "1.40.0", features = ["full"] }
zip = "2.2.0"
termimad = "0.30.0"
pulldown-cmark = "0.12.0"
