[package]
name = "zed-dl"
version = "0.1.0"
edition = "2021"

[dependencies]
octocrab = "0.43.0"
reqwest = "0.12.12"
tokio = { version = "1.43.0", features = ["full"] }
zip = "2.2.2"
termimad = "0.31.1"
pulldown-cmark = "0.12.2"
crossterm = "0.28.1"
